- name: Install python3
  apt: 
    name: "{{ item }}" 
    update_cache: yes 
    state: latest
  with_items:
    - python3
    - python3-pip
    - libpq-dev

- name: Install lib psycopg2
  pip:
    name: psycopg2
    state: present

- name: Transfer nodejs script
  copy:
    src: roles/wikijs/files/nodjs_install.sh
    dest: /tmp/nodjs_install.sh

- name: prepare NodeJS install
  shell: sh /tmp/nodjs_install.sh

- name: install NodeJS
  apt: 
    name: nodejs 
    update_cache: yes 
    state: latest

- name: Install PostgreSQL
  apt: 
    name: "{{ item }}"
    update_cache: yes 
    state: latest
  with_items: 
    - postgresql
    - postgresql-contrib
    - python3-psycopg2

- name: Create wikijs_db in PostgreSQL
  become_user: postgres
  community.general.postgresql_db:
    name: wikijs_db

- name: add wikijs user and grant right to DB
  become_user: postgres
  community.general.postgresql_user:
    db: wikijs_db
    name: wikijs
    password: "{{ DB_PASSWORD }}"
    priv: "ALL"
    expires: infinity


# Modules Error: interpreter psycopg2
#  postgresql_user:
#    db: wikijs_db
#    name: wikijs
#    password: "{ DB_PASSWORD }"
#    priv: "CONNECT/products:ALL"
#    expires: infinity

- name: install Nginx
  apt:
    pkg:
      - nginx

- name: Setup WikiJS virtual host
  template:
    src: templates/nginx_wikijs.conf
    dest: "/etc/nginx/sites-available/wikijs.conf"

- name: Enable WikiJS virtual host
  file:
    src: "/etc/nginx/sites-available/wikijs.conf"
    dest: "/etc/nginx/sites-enabled/wikijs.conf"
    state: link

- name: Restart Nginx
  systemd:
    state: restarted
    name: nginx
